### PR TITLE
Gitian Sigs for Preview

### PR DESCRIPTION
**Pull request by zathras-crypto**
I hope this is done right hehe :)

### CODE REVIEW

**Comment by dexX7** [comment]
Seems to check out. :)

I'm going to post a few more notes about it later, but there is `gverify`, which can be used to compare a bunch of results at the same time.

What do you suggest regarding the Windows build? I'm going to remove the other branch, which I accidently pushed to this repo and not mine, and create a proper PR, but if anyone compares the results, then it's a mismatch due to the installer.

**Comment by dexX7** [comment]
Ah, sorry... :S

The deleting of the remote branch closed this PR.

**Comment by zathras-crypto** [comment]
hehe no worries at all mate :)

**Comment by dexX7** [comment]
Okay, I cloned the repo locally once more, then created a new branch `0.0.9.99-8e55e3dea4`, and pushed it upstream. Can you create a new pull request?

**Pull request closed without merging**
