### PR TITLE
0.0.9.99-8e55e3dea4 build signatures of dexX7

### PR DESCRIPTION
**Pull request by dexX7**
- Release slug: 0.0.9.99-8e55e3dea4
- Commit: [8e55e3dea417f8a2e8e5bb0cc3e47e7521a017c8](https://github.com/OmniLayer/omnicore/commit/8e55e3dea417f8a2e8e5bb0cc3e47e7521a017c8)
- Signer: dexX7
- Key fingerprint: [0xF43718054C3E7C5CFB33E8257675E31CF5719832](https://pgp.mit.edu/pks/lookup?search=0xF43718054C3E7C5CFB33E8257675E31CF5719832&op=index)

```
8d4282bda770fe1a12e9a1dd6bd31b1eb8c9233f4fbd525eac3d48174b2e8c33  omnicore-0.0.9.99-dev-linux32.tar.gz
d648279cbb75f2ed4711c16f00d001cbbc99cf62277d1ff258d8239718d7cf22  omnicore-0.0.9.99-dev-linux64.tar.gz
a6bdc07d9eabba507bf74f45eadb45b28eda321dce2863d79021d84764a948b6  src/omnicore-0.0.9.99-dev.tar.gz
2072a28de226a6f61e355781a9300edc7a6d908552dc71b705f300611a68bfba  omnicore-linux-0.10-res.yml
```

```
16e81bdd20d16729cd4a579eabd0ba48e38ca8ec049b1e56398db875b7d19223  omnicore-0.0.9.99-dev-win32-setup.exe
3d431f0490ae3b8a03dbef118a58f79778306385dd728abb82059afd10810398  omnicore-0.0.9.99-dev-win32.zip
7d311ba7d6fabe0eb1fe49439e0c6c4cafc0d5deaedc4c6029f7fc6f0bd59fc8  omnicore-0.0.9.99-dev-win64-setup.exe
c9f1fb0d31209e3edbe82b14e2de593bee160268f140b185c888cda4985d7679  omnicore-0.0.9.99-dev-win64.zip
a6bdc07d9eabba507bf74f45eadb45b28eda321dce2863d79021d84764a948b6  src/omnicore-0.0.9.99-dev.tar.gz
dce44c5e737e5ec64c483b46aeec41f86deff22ef79870c1085e2df9fa048a7f  omnicore-win-0.10-res.yml
```

```
654d981ea1d831bd25dbaf1090b5a55c9d67b5a64cd7f701bf67e5dc1fc4bfca  omnicore-0.0.9.99-dev-osx-unsigned.dmg
383ecf3fb37ae1085aafd5902df8acbc9370c485ad745cd9fceb9dbf98d65abb  omnicore-0.0.9.99-dev-osx-unsigned.tar.gz
d75522982507829f11ca50a61db27035b975ab43e9c9d1422a49869626324f49  omnicore-0.0.9.99-dev-osx64.tar.gz
a6bdc07d9eabba507bf74f45eadb45b28eda321dce2863d79021d84764a948b6  src/omnicore-0.0.9.99-dev.tar.gz
d7c98e9953028e37cd6e1272e4874194c26ee76d3717c5ea75e730494d12b677  omnicore-osx-0.10-res.yml
```

### CODE REVIEW

**Comment by zathras-crypto** [comment]
FYI from my builds last night.  This is without signing.  \* = different hash to you.  I'm going to loop back around to signing next.

```
8d4282bda770fe1a12e9a1dd6bd31b1eb8c9233f4fbd525eac3d48174b2e8c33  omnicore-0.0.9.99-dev-linux32.tar.gz
d648279cbb75f2ed4711c16f00d001cbbc99cf62277d1ff258d8239718d7cf22  omnicore-0.0.9.99-dev-linux64.tar.gz
a6bdc07d9eabba507bf74f45eadb45b28eda321dce2863d79021d84764a948b6  src/omnicore-0.0.9.99-dev.tar.gz
*b6e0e63d3a7ded726b4c4092fe1089bfa354e6a60b1b92a8f4304c582caf4617  omnicore-linux-0.10-res.yml

*ca4cb835763eb61da8ebe49dd28b687aedecf90f3fbc8899467c2a27792766d1  omnicore-0.0.9.99-dev-win32-setup.exe
3d431f0490ae3b8a03dbef118a58f79778306385dd728abb82059afd10810398  omnicore-0.0.9.99-dev-win32.zip
*ac44c30d9b6e821686b31f1089de4ff1ddd1bed0b3956c5ab3ab7ce08e66ce3b  omnicore-0.0.9.99-dev-win64-setup.exe
c9f1fb0d31209e3edbe82b14e2de593bee160268f140b185c888cda4985d7679  omnicore-0.0.9.99-dev-win64.zip
a6bdc07d9eabba507bf74f45eadb45b28eda321dce2863d79021d84764a948b6  src/omnicore-0.0.9.99-dev.tar.gz
*71c8703ea17294053f8220b41abd70fab47c4a53f80f623e7014462bf9447dc0  omnicore-win-0.10-res.yml

654d981ea1d831bd25dbaf1090b5a55c9d67b5a64cd7f701bf67e5dc1fc4bfca  omnicore-0.0.9.99-dev-osx-unsigned.dmg
383ecf3fb37ae1085aafd5902df8acbc9370c485ad745cd9fceb9dbf98d65abb  omnicore-0.0.9.99-dev-osx-unsigned.tar.gz
d75522982507829f11ca50a61db27035b975ab43e9c9d1422a49869626324f49  omnicore-0.0.9.99-dev-osx64.tar.gz
a6bdc07d9eabba507bf74f45eadb45b28eda321dce2863d79021d84764a948b6  src/omnicore-0.0.9.99-dev.tar.gz
*8c388856c25da0fd0dcee8fbb20aecd05365ea5b59299f4ff783f24a8b00014a  omnicore-osx-0.10-res.yml
```

**Comment by dexX7** [comment]
Huh? The yml files produce a different hash? This is really strange, for more than one reason.

When I generate the hash manually, then it's a different one than you and I have, and this is something I tested on two machines a few minutes ago. When I check the other files, the hashes match for the binaries I created.

Can you run `sha256sum omnicore*` in the dir, where the results are moved to?

And please also run:

``` bash
~$ sha256sum omnicore* # for the binaries
~$ sha256sum ./omnicore/contrib/gitian-descriptors/* # for the gitian files
```

Right now I get:

```
8d4282bda770fe1a12e9a1dd6bd31b1eb8c9233f4fbd525eac3d48174b2e8c33  omnicore-0.0.9.99-dev-linux32.tar.gz
d648279cbb75f2ed4711c16f00d001cbbc99cf62277d1ff258d8239718d7cf22  omnicore-0.0.9.99-dev-linux64.tar.gz
d75522982507829f11ca50a61db27035b975ab43e9c9d1422a49869626324f49  omnicore-0.0.9.99-dev-osx64.tar.gz
654d981ea1d831bd25dbaf1090b5a55c9d67b5a64cd7f701bf67e5dc1fc4bfca  omnicore-0.0.9.99-dev-osx-unsigned.dmg
383ecf3fb37ae1085aafd5902df8acbc9370c485ad745cd9fceb9dbf98d65abb  omnicore-0.0.9.99-dev-osx-unsigned.tar.gz
a6bdc07d9eabba507bf74f45eadb45b28eda321dce2863d79021d84764a948b6  omnicore-0.0.9.99-dev.tar.gz
16e81bdd20d16729cd4a579eabd0ba48e38ca8ec049b1e56398db875b7d19223  omnicore-0.0.9.99-dev-win32-setup.exe
3d431f0490ae3b8a03dbef118a58f79778306385dd728abb82059afd10810398  omnicore-0.0.9.99-dev-win32.zip
7d311ba7d6fabe0eb1fe49439e0c6c4cafc0d5deaedc4c6029f7fc6f0bd59fc8  omnicore-0.0.9.99-dev-win64-setup.exe
c9f1fb0d31209e3edbe82b14e2de593bee160268f140b185c888cda4985d7679  omnicore-0.0.9.99-dev-win64.zip

880d461d071a31491fa86ae3bc2b45c5b85bb51be905532e69d6e98e390beb01  ./omnicore/contrib/gitian-descriptors/gitian-linux.yml
1e5279ca7a141c4c2b5572df0bbcfc6a938efcb8efa281ea9f04add458c5d620  ./omnicore/contrib/gitian-descriptors/gitian-osx-signer.yml
28012939e354695dd5f687d142ceb7b46551d74bebc0e9cb3aab1cfce47094b7  ./omnicore/contrib/gitian-descriptors/gitian-osx.yml
d0192624832a23fa11627811ce3685e38d4799d57c10e960d678f671e806423e  ./omnicore/contrib/gitian-descriptors/gitian-win.yml
```

**Comment by dexX7** [comment]
Hm okay.. so according to the Gitian result files the hashes of the descriptors match the manual `sha256sum`:
- [0.0.9.99-8e55e3dea4-linux/dexX7/omnicore-linux-0.10-build.assert#L7](https://github.com/OmniLayer/gitian.sigs/blob/0.0.9.99-8e55e3dea4/0.0.9.99-8e55e3dea4-linux/dexX7/omnicore-linux-0.10-build.assert#L7)
- [0.0.9.99-8e55e3dea4-osx-unsigned/dexX7/omnicore-osx-0.10-build.assert#L8](https://github.com/OmniLayer/gitian.sigs/blob/0.0.9.99-8e55e3dea4/0.0.9.99-8e55e3dea4-osx-unsigned/dexX7/omnicore-osx-0.10-build.assert#L8)
- [0.0.9.99-8e55e3dea4-win/dexX7/omnicore-win-0.10-build.assert#L9](https://github.com/OmniLayer/gitian.sigs/blob/0.0.9.99-8e55e3dea4/0.0.9.99-8e55e3dea4-win/dexX7/omnicore-win-0.10-build.assert#L9)

**Comment by zathras-crypto** [comment]
Sure dude, just at the docs be home in an hour or two & will grab the
sha256sums.

**Comment by dexX7** [comment]
Based on the other files our Windows results don't match, and hopefully this is good news, because a regtest fails for me on Win x64 ...

I'll rebuild the Windows files in the meantime.

Later then, and good health. :)

**Comment by dexX7** [comment]
My bad, I just realized I accidently pushed to this repo, and not my private one.

**Comment by dexX7** [comment]
When building on my notebook (the second time), the results match the previous results. When building on another machine the results don't match the previous ones, but I used a different Gitian version, in particular:
- https://github.com/devrandom/gitian-builder/commit/b48730064a54a01d926d60062e9feb303ede2396
- https://github.com/devrandom/gitian-builder/commit/7b82201dd7cb8cfa2f9d538983072ce358ed253e

I'm going to create a new VM on on the desktop now..

**Comment by dexX7** [comment]
I really don't get it. Also with Debian 8.1, I get again different results, but this is always limited to the win installer and x64 build.

I'll try 7.4 soon.

**Comment by zathras-crypto** [comment]
```
debian@debian:~$ sha256sum *0.0.9.99*
8d4282bda770fe1a12e9a1dd6bd31b1eb8c9233f4fbd525eac3d48174b2e8c33  omnicore-0.0.9.99-dev-linux32.tar.gz
d648279cbb75f2ed4711c16f00d001cbbc99cf62277d1ff258d8239718d7cf22  omnicore-0.0.9.99-dev-linux64.tar.gz
d75522982507829f11ca50a61db27035b975ab43e9c9d1422a49869626324f49  omnicore-0.0.9.99-dev-osx64.tar.gz
654d981ea1d831bd25dbaf1090b5a55c9d67b5a64cd7f701bf67e5dc1fc4bfca  omnicore-0.0.9.99-dev-osx-unsigned.dmg
383ecf3fb37ae1085aafd5902df8acbc9370c485ad745cd9fceb9dbf98d65abb  omnicore-0.0.9.99-dev-osx-unsigned.tar.gz
ca4cb835763eb61da8ebe49dd28b687aedecf90f3fbc8899467c2a27792766d1  omnicore-0.0.9.99-dev-win32-setup.exe
3d431f0490ae3b8a03dbef118a58f79778306385dd728abb82059afd10810398  omnicore-0.0.9.99-dev-win32.zip
ac44c30d9b6e821686b31f1089de4ff1ddd1bed0b3956c5ab3ab7ce08e66ce3b  omnicore-0.0.9.99-dev-win64-setup.exe
c9f1fb0d31209e3edbe82b14e2de593bee160268f140b185c888cda4985d7679  omnicore-0.0.9.99-dev-win64.zip
```

**Comment by zathras-crypto** [comment]
I'll run the builds again on the same VM and see if I get the same results...

**Comment by dexX7** [comment]
Wait.

**Comment by dexX7** [comment]
Before you clear the results: please keep a copy of the non-matching files. :)

**Comment by zathras-crypto** [comment]
> Based on the other files our Windows results don't match, and hopefully this is good news, because a regtest fails for me on Win x64 

Our setup EXEs didn't match but our zips did, that indicates that the binaries themselves are identical but the difference is in the installer?

**Comment by zathras-crypto** [comment]
> Before you clear the results: please keep a copy of the non-matching files. :)

Done, and is there a process for resetting anything needed before running gbuild again?

> Our setup EXEs didn't match but our zips did, that indicates that the binaries themselves are identical but the difference is in the installer?

And the yml files of course, but since the OSX & Linux & Windows binary archives _did_ all match, that's got to mean the build itself is good right?

**Comment by dexX7** [comment]
!!!!

Even though I have three different setup files (i.e. hashes), from three different builds (notebook, desktop, other Debian version), when uncompressing the setup file, and extracting the actual binaries, the files are identical.

**Comment by zathras-crypto** [comment]
Perhaps the process to create the setup executables is not deterministic?

**Comment by dexX7** [comment]
And the extracted files match those of the other archives.

> Perhaps the process to create the setup executables is not deterministic?

Seems like it, but it also works with Bitcoin Core.

**Comment by dexX7** [comment]
When comparing the files with a hex editor, there are four 4 byte differences.

Anyway, doesn't seem like a dealbreaker for the preview, I think.

**Pull request closed without merging**
